package cli

import (
	"errors"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"strings"

	"github.com/nagi1/larainspect/internal/model"
	"gopkg.in/yaml.v3"
)

func writeGeneratedConfigFile(path string, config model.AuditConfig, mode string, stdout io.Writer) error {
	if err := ensureGeneratedConfigPath(path); err != nil {
		return err
	}

	contents, err := renderGeneratedConfigYAML(config, mode)
	if err != nil {
		return err
	}
	if err := os.WriteFile(path, contents, 0o644); err != nil {
		return err
	}

	_, err = fmt.Fprintf(stdout, "Wrote %s\n", path)
	return err
}

func ensureGeneratedConfigPath(path string) error {
	if _, err := os.Stat(path); err == nil {
		return fmt.Errorf("config file %q already exists", path)
	} else if err != nil && !errors.Is(err, fs.ErrNotExist) {
		return err
	}

	directory := filepath.Dir(path)
	if directory == "." {
		return nil
	}

	return os.MkdirAll(directory, 0o755)
}

func renderGeneratedConfigYAML(config model.AuditConfig, mode string) ([]byte, error) {
	timeout := config.CommandTimeout.String()
	maxOutput := config.MaxOutputBytes
	workerLimit := config.WorkerLimit
	format := config.Format
	verbosity := string(config.Verbosity)
	scope := string(config.Scope)
	interactive := config.Interactive
	color := string(config.ColorMode)
	screenReader := config.ScreenReader
	useDefaultPaths := config.Profile.Paths.UseDefaultPatterns
	discoverNginx := config.Profile.Switches.DiscoverNginx
	discoverPHPFPM := config.Profile.Switches.DiscoverPHPFPM
	discoverMySQL := config.Profile.Switches.DiscoverMySQL
	discoverSupervisor := config.Profile.Switches.DiscoverSupervisor
	discoverSystemd := config.Profile.Switches.DiscoverSystemd

	fileCfg := fileConfig{
		Version: ptr(1),
		Server: &fileServerConfig{
			Name: maybePtr(config.Profile.Name),
			OS:   maybePtr(config.Profile.OSFamily),
		},
		Laravel: &fileLaravelConfig{
			Scope:     &scope,
			AppPath:   maybePtr(config.AppPath),
			ScanRoots: cloneStrings(config.Profile.Paths.AppScanRoots),
		},
		Identities: generatedIdentityFileConfig(config.Identities),
		Services: &fileServicesConfig{
			UseDefaultPaths: &useDefaultPaths,
			Nginx: &fileServicePaths{
				Enabled: &discoverNginx,
				Binary:  maybePtr(config.Profile.Commands.NginxBinary),
				Paths:   cloneStrings(config.Profile.Paths.NginxConfigPatterns),
			},
			PHPFPM: &fileServicePaths{
				Enabled:  &discoverPHPFPM,
				Binaries: cloneStrings(config.Profile.Commands.PHPFPMBinaries),
				Paths:    cloneStrings(config.Profile.Paths.PHPFPMPoolPatterns),
			},
			MySQL: &fileServicePaths{
				Enabled: &discoverMySQL,
				Paths:   cloneStrings(config.Profile.Paths.MySQLConfigPatterns),
			},
			Supervisor: &fileServicePaths{
				Enabled: &discoverSupervisor,
				Binary:  maybePtr(config.Profile.Commands.SupervisorBinary),
				Paths:   cloneStrings(config.Profile.Paths.SupervisorConfigPatterns),
			},
			Systemd: &fileServicePaths{
				Enabled: &discoverSystemd,
				Paths:   cloneStrings(config.Profile.Paths.SystemdUnitPatterns),
			},
		},
		Output: &fileOutputConfig{
			Format:       &format,
			Verbosity:    &verbosity,
			Interactive:  &interactive,
			Color:        &color,
			ScreenReader: &screenReader,
		},
		Advanced: &fileAdvancedConfig{
			CommandTimeout: &timeout,
			MaxOutputBytes: &maxOutput,
			WorkerLimit:    &workerLimit,
		},
	}

	encoded, err := yaml.Marshal(fileCfg)
	if err != nil {
		return nil, err
	}

	header := fmt.Sprintf("# Generated by larainspect %s. Review paths and service binaries before the first audit.\n\n", mode)
	return append([]byte(header), encoded...), nil
}

func generatedIdentityFileConfig(identities model.IdentityConfig) *fileIdentitiesConfig {
	identities = normalizeIdentityConfig(identities)
	if len(identities.DeployUsers) == 0 && len(identities.RuntimeUsers) == 0 && len(identities.RuntimeGroups) == 0 && len(identities.WebUsers) == 0 && len(identities.WebGroups) == 0 {
		return nil
	}

	return &fileIdentitiesConfig{
		DeployUsers:   cloneStrings(identities.DeployUsers),
		RuntimeUsers:  cloneStrings(identities.RuntimeUsers),
		RuntimeGroups: cloneStrings(identities.RuntimeGroups),
		WebUsers:      cloneStrings(identities.WebUsers),
		WebGroups:     cloneStrings(identities.WebGroups),
	}
}

func maybePtr(value string) *string {
	trimmed := strings.TrimSpace(value)
	if trimmed == "" {
		return nil
	}

	return &trimmed
}

func ptr[T any](value T) *T {
	return &value
}
