package cli

import (
	"bytes"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/nagi1/larainspect/internal/model"
)

func TestRenderGeneratedConfigYAMLIncludesIdentities(t *testing.T) {
	t.Parallel()

	config := model.DefaultAuditConfig()
	config.CommandTimeout = 5 * time.Second
	config.Profile.Name = "example-host"
	config.Profile.OSFamily = "debian"
	config.Profile.Paths.AppScanRoots = []string{"/var/www"}
	config.Identities = model.IdentityConfig{
		DeployUsers:   []string{"forge"},
		RuntimeUsers:  []string{"forge"},
		RuntimeGroups: []string{"forge"},
		WebUsers:      []string{"www-data"},
		WebGroups:     []string{"www-data"},
	}

	contents, err := renderGeneratedConfigYAML(config, "setup")
	if err != nil {
		t.Fatalf("renderGeneratedConfigYAML() error = %v", err)
	}

	rendered := string(contents)
	if !strings.Contains(rendered, "Generated by larainspect setup") {
		t.Fatalf("expected generated header, got %q", rendered)
	}
	if !strings.Contains(rendered, "identities:") || !strings.Contains(rendered, "deploy_users:") {
		t.Fatalf("expected identities section, got %q", rendered)
	}
	if !strings.Contains(rendered, "www-data") {
		t.Fatalf("expected rendered web identity, got %q", rendered)
	}
}

func TestEnsureGeneratedConfigPathRejectsExistingFile(t *testing.T) {
	t.Parallel()

	configPath := filepath.Join(t.TempDir(), "larainspect.yaml")
	writeConfigFileForTest(t, configPath, "version: 1\n")

	if err := ensureGeneratedConfigPath(configPath); err == nil {
		t.Fatal("expected ensureGeneratedConfigPath() to reject existing files")
	}
}

func TestWriteGeneratedConfigFileWritesOutput(t *testing.T) {
	t.Parallel()

	config := model.DefaultAuditConfig()
	config.CommandTimeout = 5 * time.Second
	config.Profile.Name = "example-host"
	config.Profile.OSFamily = "debian"

	configPath := filepath.Join(t.TempDir(), "nested", "larainspect.yaml")
	var stdout bytes.Buffer
	if err := writeGeneratedConfigFile(configPath, config, "init", &stdout); err != nil {
		t.Fatalf("writeGeneratedConfigFile() error = %v", err)
	}
	if !strings.Contains(stdout.String(), "Wrote ") {
		t.Fatalf("expected success output, got %q", stdout.String())
	}
}

func TestParseNginxUserDirectiveIgnoresInlineComments(t *testing.T) {
	t.Parallel()

	userName, groupName := parseNginxUserDirective("worker_processes auto;\nuser www-data nginx; # comment\n")
	if userName != "www-data" || groupName != "nginx" {
		t.Fatalf("unexpected nginx user directive result user=%q group=%q", userName, groupName)
	}
}

func TestResolveGeneratedIdentityConfigPromptsForMissingValues(t *testing.T) {
	t.Parallel()

	var stderr bytes.Buffer
	identities, err := resolveGeneratedIdentityConfig(
		strings.NewReader("deploy\nruntime\nruntime-group\nweb\nweb-group\n"),
		&stderr,
		presetVPS,
		hostInspector{},
		model.DefaultAuditConfig(),
	)
	if err != nil {
		t.Fatalf("resolveGeneratedIdentityConfig() error = %v", err)
	}

	if len(identities.DeployUsers) != 1 || identities.DeployUsers[0] != "deploy" {
		t.Fatalf("unexpected deploy users %+v", identities.DeployUsers)
	}
	if len(identities.WebGroups) != 1 || identities.WebGroups[0] != "web-group" {
		t.Fatalf("unexpected web groups %+v", identities.WebGroups)
	}
	if !strings.Contains(stderr.String(), "Could not confidently detect all deploy, runtime, and web identities") {
		t.Fatalf("expected identity guidance, got %q", stderr.String())
	}
}
