package html

import (
	"fmt"
	"html"
	"io"
	"strings"

	"github.com/nagi1/larainspect/internal/controls"
	"github.com/nagi1/larainspect/internal/model"
	"github.com/nagi1/larainspect/internal/report"
	"github.com/nagi1/larainspect/internal/report/reportfmt"
)

var _ report.Reporter = Reporter{}

// Reporter generates a self-contained standalone HTML report.
type Reporter struct{}

func NewReporter() Reporter {
	return Reporter{}
}

func (r Reporter) Format() string {
	return "html"
}

func (r Reporter) Render(w io.Writer, report model.Report) error {
	var sb strings.Builder
	writeDocument(&sb, report)
	_, err := io.WriteString(w, sb.String())
	return err
}

func writeDocument(sb *strings.Builder, report model.Report) {
	sb.WriteString(`<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Larainspect Security Report</title>
<style>
`)
	sb.WriteString(embeddedCSS)
	sb.WriteString(`
</style>
</head>
<body>
`)

	writeSidebar(sb, report)
	sb.WriteString(`<main class="main">
`)
	writeHeader(sb, report)
	writeOverview(sb, report)
	writeHostInfo(sb, report)
	writeFindingClassSection(sb, "Direct Findings", "direct", report.DirectFindings)
	writeFindingClassSection(sb, "Heuristic Findings", "heuristic", report.HeuristicFindings)
	writeFindingClassSection(sb, "Possible Compromise Indicators", "compromise", report.CompromiseIndicators)
	writeUnknownsSection(sb, report.Unknowns)
	writeFooter(sb)
	sb.WriteString(`</main>
</body>
</html>`)
}

func writeSidebar(sb *strings.Builder, report model.Report) {
	sb.WriteString(`<aside class="sidebar">
  <div class="sidebar-logo">LARAINSPECT</div>
  <nav class="toc">
    <div class="toc-title">Report</div>
    <a href="#overview" class="toc-link">Overview</a>
    <a href="#host" class="toc-link">Host Info</a>
    <div class="toc-title" style="margin-top:20px;">Findings</div>
`)
	writeTocEntry(sb, "direct", "Direct Findings", len(report.DirectFindings))
	writeTocEntry(sb, "heuristic", "Heuristic Findings", len(report.HeuristicFindings))
	writeTocEntry(sb, "compromise", "Compromise Indicators", len(report.CompromiseIndicators))
	if len(report.Unknowns) > 0 {
		writeTocEntry(sb, "unknowns", "Unknowns", len(report.Unknowns))
	}
	sb.WriteString(`  </nav>
  <div class="sidebar-footer">Generated by Larainspect ` + model.SchemaVersion + `</div>
</aside>
`)
}

func writeTocEntry(sb *strings.Builder, slug, label string, count int) {
	sb.WriteString(fmt.Sprintf(`    <a href="#%s" class="toc-link"><span>%s</span><span class="toc-count">%d</span></a>
`, slug, esc(label), count))
}

func writeHeader(sb *strings.Builder, report model.Report) {
	sb.WriteString(`<header class="header">
  <h1>Security Audit Report</h1>
  <p class="header-meta">`)
	sb.WriteString(fmt.Sprintf(`%s &middot; %s &middot; %s &middot; %s`,
		esc(reportfmt.DefaultString(report.Host.Hostname, "unknown host")),
		esc(reportfmt.DefaultString(report.Host.OS, "unknown OS")),
		report.Duration,
		report.GeneratedAt.Format("2006-01-02 15:04:05 UTC")))
	sb.WriteString(`</p>
</header>
`)
}

func writeOverview(sb *strings.Builder, report model.Report) {
	total := report.Summary.TotalFindings
	sb.WriteString(`<section id="overview" class="section">
  <h2 class="section-title">Overview</h2>
  <div class="stats-grid">
`)
	writeStatCard(sb, "total", "Total Findings", total)
	for _, sev := range reportfmt.OrderedSeverities() {
		c := report.Summary.SeverityCounts[sev]
		writeStatCard(sb, severityClass(sev), string(sev), c)
	}
	if report.Summary.Unknowns > 0 {
		writeStatCard(sb, "unknown", "Unknowns", report.Summary.Unknowns)
	}
	sb.WriteString(`  </div>
`)

	// Severity bar
	if total > 0 {
		sb.WriteString(`  <div class="severity-bar">
`)
		for _, sev := range reportfmt.OrderedSeverities() {
			c := report.Summary.SeverityCounts[sev]
			if c == 0 {
				continue
			}
			pct := float64(c) / float64(total) * 100
			sb.WriteString(fmt.Sprintf(`    <div class="bar-seg %s" style="width:%.1f%%" title="%d %s"></div>
`, severityClass(sev), pct, c, sev))
		}
		sb.WriteString(`  </div>
`)
	}

	// Finding class breakdown
	sb.WriteString(`  <div class="class-breakdown">
    <span class="class-label">Breakdown:</span>
`)
	sb.WriteString(fmt.Sprintf(`    <span class="class-tag">%d direct</span>
`, report.Summary.DirectFindings))
	sb.WriteString(fmt.Sprintf(`    <span class="class-tag">%d heuristic</span>
`, report.Summary.HeuristicFindings))
	sb.WriteString(fmt.Sprintf(`    <span class="class-tag">%d compromise indicators</span>
`, report.Summary.CompromiseIndicators))
	sb.WriteString(fmt.Sprintf(`    <span class="class-tag">%d unknowns</span>
`, report.Summary.Unknowns))
	sb.WriteString(`  </div>
</section>
`)
}

func writeStatCard(sb *strings.Builder, class, label string, count int) {
	sb.WriteString(fmt.Sprintf(`    <div class="stat-card %s"><div class="stat-num">%d</div><div class="stat-label">%s</div></div>
`, class, count, esc(label)))
}

func writeHostInfo(sb *strings.Builder, report model.Report) {
	sb.WriteString(`<section id="host" class="section">
  <h2 class="section-title">Host Info</h2>
  <div class="info-grid">
`)
	writeInfoRow(sb, "Hostname", reportfmt.DefaultString(report.Host.Hostname, "unknown"))
	writeInfoRow(sb, "OS", reportfmt.DefaultString(report.Host.OS, "unknown"))
	writeInfoRow(sb, "Architecture", reportfmt.DefaultString(report.Host.Arch, "unknown"))
	writeInfoRow(sb, "Duration", report.Duration)
	writeInfoRow(sb, "Result", reportfmt.ReportResultLabel(report))
	sb.WriteString(`  </div>
</section>
`)
}

func writeFindingClassSection(sb *strings.Builder, title, slug string, findings []model.Finding) {
	sb.WriteString(fmt.Sprintf(`<section id="%s" class="section">
  <div class="cat-header">
    <h2 class="section-title">%s</h2>
    <span class="cat-count">%d finding%s</span>
  </div>
`, slug, esc(title), len(findings), plural(len(findings))))

	if len(findings) == 0 {
		sb.WriteString(`  <p class="empty-note">None.</p>
`)
		sb.WriteString(`</section>
`)
		return
	}

	sorted := append([]model.Finding(nil), findings...)
	reportfmt.SortFindings(sorted)

	for idx, f := range sorted {
		writeFindingCard(sb, f, slug, idx)
	}

	sb.WriteString(`</section>
`)
}

func writeFindingCard(sb *strings.Builder, f model.Finding, slug string, idx int) {
	sevClass := severityClass(f.Severity)
	findingID := fmt.Sprintf("%s-%d", slug, idx)

	sb.WriteString(fmt.Sprintf(`  <details class="finding" id="%s">
    <summary class="finding-summary">
      <span class="badge %s">%s</span>
      <span class="finding-title">%s</span>
      <span class="finding-id">%s</span>
      <span class="finding-confidence">%s</span>
      <svg class="chevron" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="6 9 12 15 18 9"/></svg>
    </summary>
    <div class="finding-body">
`, findingID, sevClass, esc(string(f.Severity)), esc(f.Title), esc(f.CheckID), esc(string(f.Confidence))))

	sb.WriteString(fmt.Sprintf(`      <p class="finding-desc">%s</p>
`, esc(f.Why)))

	writeEvidenceBlock(sb, f.Evidence)
	writeAffectedBlock(sb, f.Affected)
	writeControlsBlock(sb, controls.ForFinding(f.CheckID, f.ID))

	if f.Remediation != "" {
		sb.WriteString(fmt.Sprintf(`      <div class="finding-fix">
        <div class="fix-label">Remediation</div>
        <p>%s</p>
      </div>
`, esc(f.Remediation)))
	}

	sb.WriteString(`    </div>
  </details>
`)
}

func writeUnknownsSection(sb *strings.Builder, unknowns []model.Unknown) {
	sb.WriteString(fmt.Sprintf(`<section id="unknowns" class="section">
  <div class="cat-header">
    <h2 class="section-title">Unknowns</h2>
    <span class="cat-count">%d item%s</span>
  </div>
`, len(unknowns), plural(len(unknowns))))

	if len(unknowns) == 0 {
		sb.WriteString(`  <p class="empty-note">No unknowns — all checks completed successfully.</p>
`)
		sb.WriteString(`</section>
`)
		return
	}

	for idx, u := range unknowns {
		writeUnknownCard(sb, u, idx)
	}

	sb.WriteString(`</section>
`)
}

func writeUnknownCard(sb *strings.Builder, u model.Unknown, idx int) {
	sb.WriteString(fmt.Sprintf(`  <details class="finding unknown-card" id="unknown-%d">
    <summary class="finding-summary">
      <span class="badge unknown">UNKNOWN</span>
      <span class="finding-title">%s</span>
      <span class="finding-id">%s</span>
      <span class="finding-confidence">%s</span>
      <svg class="chevron" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="6 9 12 15 18 9"/></svg>
    </summary>
    <div class="finding-body">
`, idx, esc(u.Title), esc(u.CheckID), esc(string(u.Error))))

	sb.WriteString(fmt.Sprintf(`      <p class="finding-desc">%s</p>
`, esc(u.Reason)))

	writeEvidenceBlock(sb, u.Evidence)
	writeAffectedBlock(sb, u.Affected)

	sb.WriteString(`    </div>
  </details>
`)
}

func writeControlsBlock(sb *strings.Builder, relatedControls []controls.Control) {
	if len(relatedControls) == 0 {
		return
	}

	sb.WriteString(`      <div class="meta-block">
        <div class="fix-label">Controls</div>
        <ul class="evidence-list">
`)
	for _, control := range relatedControls {
		sb.WriteString(fmt.Sprintf(`          <li><code>%s</code> <span class="finding-confidence">%s</span> %s</li>
`, esc(control.ID), esc(string(control.Status)), esc(control.Name)))
	}
	sb.WriteString(`        </ul>
      </div>
`)
}

func writeEvidenceBlock(sb *strings.Builder, evidence []model.Evidence) {
	if len(evidence) == 0 {
		return
	}
	sb.WriteString(`      <div class="finding-evidence">
        <div class="evidence-label">Evidence</div>
`)
	for _, e := range evidence {
		sb.WriteString(fmt.Sprintf(`        <div class="evidence-item"><span class="evidence-key">%s:</span> <code>%s</code></div>
`, esc(e.Label), esc(e.Detail)))
	}
	sb.WriteString(`      </div>
`)
}

func writeAffectedBlock(sb *strings.Builder, affected []model.Target) {
	if len(affected) == 0 {
		return
	}
	sb.WriteString(`      <div class="finding-affected">
        <div class="affected-label">Affected</div>
`)
	for _, t := range affected {
		sb.WriteString(fmt.Sprintf(`        <div class="affected-item"><code>%s</code></div>
`, esc(reportfmt.DescribeTarget(t))))
	}
	sb.WriteString(`      </div>
`)
}

func writeFooter(sb *strings.Builder) {
	sb.WriteString(`<footer class="report-footer">
  <p>Generated by <a href="https://github.com/nagi1/larainspect" target="_blank" rel="noopener">Larainspect</a> ` + model.SchemaVersion + `</p>
</footer>
`)
}

// Helpers

func esc(s string) string {
	return html.EscapeString(s)
}

func severityClass(s model.Severity) string {
	return strings.ToLower(string(s))
}

func plural(n int) string {
	if n == 1 {
		return ""
	}
	return "s"
}

func writeInfoRow(sb *strings.Builder, label, value string) {
	sb.WriteString(fmt.Sprintf(`    <div class="info-row"><span class="info-label">%s</span><span class="info-value">%s</span></div>
`, label, esc(value)))
}
